### PR TITLE
Major refactoring

### PR DESCRIPTION
**Pull request by wucke13**
Solves #4 & #5

+ -> self contained shell script
+ add symlink to FHS to save time upon multiple calls
+ still missing a check whether nix-index needs a refresh

### CODE REVIEW

**Comment by wucke13** [comment]
@Lassulus ping
Btw, what do you think about the rust rewrite? Are you fine if it keeps the `nix-autobahn` name? Do you want it to be in this repo?

**Comment by Lassulus** [comment]
uh, I should start watching my own repositories, I'm currently on holiday and its quite early here, hopefully I will check this later

**Comment by wucke13** [comment]
Take your time and enjoy the vacation :sun_with_face:. If the Rust code is an option, we should continue the discussion in #7 btw.

**Comment by Clausinho** [comment]
@wucke13 hey, you never released the refactoring, what are you using currently for this usecase?

**Comment by wucke13** [comment]
@Clausinho nothing, I just stopped using it 😅

**Pull request closed without merging**
